name: door_with_rfid
description: IoT Door Control with RFID.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar_v2: ^4.2.8
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  lottie: ^2.6.0
  awesome_notifications: any
  awesome_notifications_core: ^0.8.1
  objectbox: ^2.3.1
  objectbox_flutter_libs: any
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  objectbox_generator: ^2.3.1

flutter:
  assets:
    - assets/anims/
    - assets/icons/
    - assets/illustrations/

  uses-material-design: true
  fonts:
    - family: sansSerif
      fonts:
        - asset: assets/fonts/sans_serif.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf

objectbox:
# Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: models/